name: Create Beta Package

on:
  create:

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  is_beta:
    if: contains(github.ref, 'beta') == true
    runs-on: ubuntu-latest

    steps:
    - name: Check
      run: |
        echo ${{ github.event }}
        echo ${{ github.event_name }}
        echo ${{ github.event_path }}
        echo ${{ github.ref }}

    - name: Remove Changelog
      run: rm -f CHANGELOG.md

  mainline:
    needs: is_beta
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create Mainline Package
      uses: BigWigsMods/packager@v1.0.3
      with:
        args: -m .pkgmeta

  tbc:
    needs: is_beta
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create TBC Package
      uses: BigWigsMods/packager@v1.0.3
      with:
        args: -m .pkgmeta-tbc

  vanilla:
    needs: is_beta
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create Vanilla Package
      uses: BigWigsMods/packager@v1.0.3
      with:
        args: -m .pkgmeta-vanilla
