name: Create Beta Package

on:
  create:

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  is_beta:
    if: contains(github.ref, 'beta') == true
    runs-on: ubuntu-latest

    steps:
    - name: Check
      run: |
        echo ${{ github.event }}
        echo ${{ github.event_name }}
        echo ${{ github.event_path }}
        echo ${{ github.ref }}

  mainline:
    needs: is_beta
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Remove Changelog
      run: rm -f CHANGELOG.md

    - name: Create Mainline Package
      uses: BigWigsMods/packager@v2

  # wrath:
  #   needs: is_beta
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Remove Changelog
  #     run: rm -f CHANGELOG.md

  #   - name: Create Wrath Package
  #     uses: BigWigsMods/packager@v2
  #     with:
  #       args: -g wrath -m .pkgmeta-wrath

  # vanilla:
  #   needs: is_beta
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Remove Changelog
  #     run: rm -f CHANGELOG.md

  #   - name: Create Vanilla Package
  #     uses: BigWigsMods/packager@v2
  #     with:
  #       args: -g classic -m .pkgmeta-vanilla
