name: Parse Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Parse Docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -s https://raw.githubusercontent.com/Gethe/lua-doc-parser/https/parse.py -o parse.py
        curl -s https://raw.githubusercontent.com/Gethe/lua-doc-parser/https/build.sh | bash
